CREATE TABLE passwords
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    password    VARCHAR(255)                            NOT NULL,
    create_date TIMESTAMP WITHOUT TIME ZONE,
    end_date    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_passwords PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                  VARCHAR(50)                             NOT NULL,
    can_manage_users      BOOLEAN                                 NOT NULL,
    can_modify_main_pages BOOLEAN                                 NOT NULL,
    upload_files          BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE user_passwords
(
    password_id BIGINT NOT NULL,
    user_id     BIGINT NOT NULL
);

CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE usernames
(
    username_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username    VARCHAR(255)                            NOT NULL,
    user_id     BIGINT,
    create_date TIMESTAMP WITHOUT TIME ZONE,
    end_date    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_usernames PRIMARY KEY (username_id)
);

CREATE TABLE users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name      VARCHAR(255),
    last_name       VARCHAR(255),
    email           VARCHAR(255)                            NOT NULL,
    username_id     BIGINT,
    create_date     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_login_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE user_passwords
    ADD CONSTRAINT uc_user_passwords_password UNIQUE (password_id);

ALTER TABLE usernames
    ADD CONSTRAINT uc_usernames_username UNIQUE (username);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE passwords
    ADD CONSTRAINT FK_PASSWORDS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE usernames
    ADD CONSTRAINT FK_USERNAMES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_USERNAME FOREIGN KEY (username_id) REFERENCES usernames (username_id);

ALTER TABLE user_passwords
    ADD CONSTRAINT fk_usepas_on_password FOREIGN KEY (password_id) REFERENCES passwords (id);

ALTER TABLE user_passwords
    ADD CONSTRAINT fk_usepas_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);